const RENTAL_TIME_IN_MINUTES = 360;
const DECIMALS = 19;
const RENTAL_FEE = 3000 * Math.pow(10, DECIMALS);
const ESCROW_AMOUNT = RENTAL_FEE * 3;
const RATE = 314159;

module.exports = {
  RENTAL_FEE,
  RENTAL_TIME_IN_MINUTES,
  DECIMALS,
  ESCROW_AMOUNT,
  RATE
};